import type { FormulaCard } from '@/types';

/* =====================================================================
   MATHGITA — CẨM NANG CÔNG THỨC ĐIỂM 10
   Mỗi thẻ công thức gồm: công thức — điều kiện — dùng khi nào — bẫy.
   ===================================================================== */

export const FORMULAS: FormulaCard[] = [
  /* ------------------------------ LỚP 6 ------------------------------ */
  { id: 'f6-1', grade: 6, strand: 'SO_DAI_SO', topic: 'Lũy thừa', name: 'Nhân hai lũy thừa cùng cơ số', formula: '$a^{m}\\cdot a^{n}=a^{m+n}$', usage: 'Rút gọn tích các lũy thừa cùng cơ số.', trap: 'Cộng số mũ, không nhân số mũ.' },
  { id: 'f6-2', grade: 6, strand: 'SO_DAI_SO', topic: 'Lũy thừa', name: 'Chia hai lũy thừa cùng cơ số', formula: '$a^{m}:a^{n}=a^{m-n}$', condition: '$a\\ne0$, $m\\ge n$', usage: 'Rút gọn thương các lũy thừa.', trap: 'Quên điều kiện $a\\ne0$.' },
  { id: 'f6-3', grade: 6, strand: 'SO_DAI_SO', topic: 'Tính chia hết', name: 'Dấu hiệu chia hết cho 3 và 9', formula: 'Tổng các chữ số chia hết cho 3 (hoặc 9)', usage: 'Tìm chữ số chưa biết, xét tính chia hết.', trap: 'Chia hết cho 9 thì chia hết cho 3, chiều ngược lại sai.' },
  { id: 'f6-4', grade: 6, strand: 'SO_DAI_SO', topic: 'ƯCLN – BCNN', name: 'Quy tắc tìm ƯCLN', formula: 'Thừa số nguyên tố **chung**, số mũ **nhỏ nhất**', usage: 'Bài toán chia đều thành nhiều phần nhất.', trap: 'Nhầm với BCNN (chung và riêng, mũ lớn nhất).' },
  { id: 'f6-5', grade: 6, strand: 'SO_DAI_SO', topic: 'ƯCLN – BCNN', name: 'Liên hệ ƯCLN và BCNN', formula: '$\\text{ƯCLN}(a,b)\\cdot\\text{BCNN}(a,b)=a\\cdot b$', usage: 'Tìm nhanh một trong hai khi biết cái còn lại.', trap: 'Chỉ đúng cho **hai** số, không mở rộng cho ba số.' },
  { id: 'f6-6', grade: 6, strand: 'SO_DAI_SO', topic: 'Số ước', name: 'Đếm số ước của một số', formula: '$n=p_1^{a_1}p_2^{a_2}\\cdots p_k^{a_k}\\Rightarrow$ số ước $=(a_1+1)(a_2+1)\\cdots(a_k+1)$', usage: 'Câu hỏi “có bao nhiêu ước”.', trap: 'Quên cộng 1 vào mỗi số mũ.' },
  { id: 'f6-7', grade: 6, strand: 'SO_DAI_SO', topic: 'Phân số', name: 'Hai bài toán cơ bản về phân số', formula: '$\\f{m}{n}$ của $a$ là $a\\cdot\\f{m}{n}$ ; biết $\\f{m}{n}$ của $x$ bằng $b$ thì $x=b:\\f{m}{n}$', usage: 'Bài toán thực tế về phần – toàn thể.', trap: 'Nhầm chiều nhân/chia.' },
  { id: 'f6-8', grade: 6, strand: 'SO_DAI_SO', topic: 'Phân số', name: 'Tổng sai phân', formula: '$\\f{1}{n(n+1)}=\\f{1}{n}-\\f{1}{n+1}$', usage: 'Tính tổng dãy phân số có quy luật.', trap: 'Chỉ áp dụng khi mẫu là tích hai số liên tiếp (hoặc cách đều).' },
  { id: 'f6-9', grade: 6, strand: 'SO_DAI_SO', topic: 'Tỉ số phần trăm', name: 'Tăng – giảm liên tiếp', formula: '$A(1\\pm\\f{m}{100})(1\\pm\\f{n}{100})$', usage: 'Giảm giá nhiều lần, lãi kép.', trap: 'Không được cộng dồn phần trăm của hai lần.' },
  { id: 'f6-10', grade: 6, strand: 'HINH_HOC', topic: 'Diện tích', name: 'Diện tích hình thoi', formula: '$S=\\f{1}{2}mn$ ($m$, $n$ là hai đường chéo)', usage: 'Khi đề cho hai đường chéo.', trap: 'Quên hệ số $\\f{1}{2}$.' },
  { id: 'f6-11', grade: 6, strand: 'HINH_HOC', topic: 'Diện tích', name: 'Diện tích hình thang', formula: '$S=\\f{(a+b)h}{2}$', usage: 'Hai đáy $a$, $b$ và chiều cao $h$.', trap: 'Lấy cạnh bên làm chiều cao.' },
  { id: 'f6-12', grade: 6, strand: 'HINH_HOC', topic: 'Đoạn thẳng', name: 'Hệ thức cộng đoạn thẳng', formula: '$M$ nằm giữa $A$, $B$ $\\Leftrightarrow AM+MB=AB$', usage: 'Tính độ dài, chứng minh trung điểm.', trap: 'Dùng hệ thức khi chưa lập luận điểm nằm giữa.' },

  /* ------------------------------ LỚP 7 ------------------------------ */
  { id: 'f7-1', grade: 7, strand: 'SO_DAI_SO', topic: 'Lũy thừa', name: 'Lũy thừa của lũy thừa', formula: '$(x^{m})^{n}=x^{mn}$', usage: 'Đưa về cùng cơ số khi so sánh.', trap: 'Nhầm với $x^{m}\\cdot x^{n}=x^{m+n}$.' },
  { id: 'f7-2', grade: 7, strand: 'SO_DAI_SO', topic: 'Giá trị tuyệt đối', name: 'Định nghĩa hai nhánh', formula: '$\\abs{x}=x$ nếu $x\\ge0$ ; $\\abs{x}=-x$ nếu $x<0$', usage: 'Giải phương trình, bất phương trình chứa dấu $\\abs{\\ }$.', trap: 'Quên nhánh âm khi giải $\\abs{A}=a$.' },
  { id: 'f7-3', grade: 7, strand: 'SO_DAI_SO', topic: 'Giá trị tuyệt đối', name: 'Bất đẳng thức tam giác cho số', formula: '$\\abs{a}+\\abs{b}\\ge\\abs{a+b}$', condition: 'Dấu “=” khi $a$, $b$ cùng dấu', usage: 'Tìm GTNN của tổng hai giá trị tuyệt đối.', trap: 'Quên nêu điều kiện dấu bằng.' },
  { id: 'f7-4', grade: 7, strand: 'SO_DAI_SO', topic: 'Tỉ lệ thức', name: 'Tính chất dãy tỉ số bằng nhau', formula: '$\\f{a}{b}=\\f{c}{d}=\\f{a+c}{b+d}=\\f{a-c}{b-d}$', condition: '$b+d\\ne0$, $b-d\\ne0$', usage: 'Bài toán chia phần theo tỉ lệ.', trap: 'Áp dụng cho **tích** — sai; phải đặt tham số $t$.' },
  { id: 'f7-5', grade: 7, strand: 'SO_DAI_SO', topic: 'Đại lượng tỉ lệ', name: 'Tỉ lệ nghịch', formula: '$x_1y_1=x_2y_2=a$', usage: 'Bài toán người – việc – thời gian, vận tốc – thời gian.', trap: '“Tỉ lệ nghịch với $m;n;p$” = “tỉ lệ thuận với $\\f{1}{m};\\f{1}{n};\\f{1}{p}$”.' },
  { id: 'f7-6', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Bất đẳng thức tam giác', formula: '$\\abs{b-c}<a<b+c$', usage: 'Xét ba độ dài có lập thành tam giác không.', trap: 'Chỉ cần kiểm tra với cạnh lớn nhất.' },
  { id: 'f7-7', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Trọng tâm chia trung tuyến', formula: '$AG=\\f{2}{3}AM$ ; $GM=\\f{1}{3}AM$', usage: 'Tính độ dài liên quan trọng tâm.', trap: 'Nhầm tỉ số $\\f{2}{3}$ và $\\f{1}{2}$.' },
  { id: 'f7-8', grade: 7, strand: 'HINH_HOC', topic: 'Đường thẳng song song', name: 'Tính chất hai đường song song', formula: 'So le trong bằng nhau; đồng vị bằng nhau; trong cùng phía bù nhau', usage: 'Tính số đo góc trong hình có hai đường song song.', trap: 'Lẫn chiều “dấu hiệu” và chiều “tính chất”.' },
  { id: 'f7-9', grade: 7, strand: 'HINH_HOC', topic: 'Hình khối', name: 'Lăng trụ đứng', formula: '$S_{xq}=C_{\\text{đáy}}\\cdot h$ ; $V=S_{\\text{đáy}}\\cdot h$', usage: 'Bài toán lều trại, thùng chứa.', trap: '$1\\,dm^{3}=1$ lít.' },

  /* ------------------------------ LỚP 8 ------------------------------ */
  { id: 'f8-1', grade: 8, strand: 'SO_DAI_SO', topic: 'Hằng đẳng thức', name: 'Bình phương của một tổng', formula: '$(A+B)^{2}=A^{2}+2AB+B^{2}$', usage: 'Khai triển, hoàn thành bình phương.', trap: 'Quên hạng tử $2AB$.' },
  { id: 'f8-2', grade: 8, strand: 'SO_DAI_SO', topic: 'Hằng đẳng thức', name: 'Hiệu hai bình phương', formula: '$A^{2}-B^{2}=(A-B)(A+B)$', usage: 'Phân tích nhân tử, tính nhanh.', trap: '$A^{2}+B^{2}$ không phân tích được trên $\\R$.' },
  { id: 'f8-3', grade: 8, strand: 'SO_DAI_SO', topic: 'Hằng đẳng thức', name: 'Tổng hai lập phương', formula: '$A^{3}+B^{3}=(A+B)(A^{2}-AB+B^{2})$', usage: 'Phân tích nhân tử bậc ba.', trap: 'Ngoặc thứ hai là bình phương **thiếu**: $-AB$ chứ không phải $-2AB$.' },
  { id: 'f8-4', grade: 8, strand: 'SO_DAI_SO', topic: 'Cực trị', name: 'Hoàn thành bình phương', formula: '$x^{2}+bx=\\left(x+\\f{b}{2}\\right)^{2}-\\f{b^{2}}{4}$', usage: 'Tìm GTNN, GTLN của tam thức bậc hai.', trap: 'Quên trừ lại $\\f{b^{2}}{4}$.' },
  { id: 'f8-5', grade: 8, strand: 'SO_DAI_SO', topic: 'Năng suất', name: 'Cộng năng suất', formula: '$\\f{1}{t_1}+\\f{1}{t_2}=\\f{1}{t}$', usage: 'Bài toán làm chung – làm riêng.', trap: 'Không bao giờ cộng thời gian.' },
  { id: 'f8-6', grade: 8, strand: 'SO_DAI_SO', topic: 'Hàm số', name: 'Vị trí tương đối hai đường thẳng', formula: 'Song song $\\Leftrightarrow a=a\'$, $b\\ne b\'$ ; Cắt nhau $\\Leftrightarrow a\\ne a\'$', usage: 'Bài toán tham số về đường thẳng.', trap: 'Quên điều kiện $b\\ne b\'$ khi nói song song.' },
  { id: 'f8-7', grade: 8, strand: 'HINH_HOC', topic: 'Thalès', name: 'Định lí Thalès', formula: '$MN\\para BC\\Rightarrow\\f{AM}{MB}=\\f{AN}{NC}$', usage: 'Tính độ dài trong hình có đường song song.', trap: 'Viết sai thứ tự tương ứng của tỉ số.' },
  { id: 'f8-8', grade: 8, strand: 'HINH_HOC', topic: 'Phân giác', name: 'Tính chất đường phân giác', formula: '$\\f{DB}{DC}=\\f{AB}{AC}$', condition: '$AD$ là phân giác góc $A$', usage: 'Tính độ dài đoạn bị chia bởi phân giác.', trap: 'Nhầm thứ tự tử – mẫu.' },
  { id: 'f8-9', grade: 8, strand: 'HINH_HOC', topic: 'Đồng dạng', name: 'Tỉ số diện tích hai tam giác đồng dạng', formula: '$\\f{S_1}{S_2}=k^{2}$', condition: '$k$ là tỉ số đồng dạng', usage: 'So sánh diện tích.', trap: 'Dùng $k$ thay vì $k^{2}$.' },
  { id: 'f8-10', grade: 8, strand: 'HINH_HOC', topic: 'Pythagore', name: 'Định lí Pythagore', formula: '$BC^{2}=AB^{2}+AC^{2}$', condition: '$\\tri ABC$ vuông tại $A$', usage: 'Tính cạnh, kiểm tra tam giác vuông.', trap: 'Cạnh huyền luôn là cạnh lớn nhất.' },

  /* ------------------------------ LỚP 9 ------------------------------ */
  { id: 'f9-1', grade: 9, strand: 'SO_DAI_SO', topic: 'Căn thức', name: 'Hằng đẳng thức căn', formula: '$\\s{A^{2}}=\\abs{A}$', usage: 'Rút gọn căn thức.', trap: 'Viết $\\s{A^{2}}=A$ khi chưa biết dấu của $A$.' },
  { id: 'f9-2', grade: 9, strand: 'SO_DAI_SO', topic: 'Căn thức', name: 'Trục căn thức ở mẫu', formula: '$\\f{C}{\\s{A}\\pm\\s{B}}=\\f{C(\\s{A}\\mp\\s{B})}{A-B}$', condition: '$A\\ne B$, $A,B\\ge0$', usage: 'Khử căn ở mẫu.', trap: 'Quên đổi dấu ở biểu thức liên hợp.' },
  { id: 'f9-3', grade: 9, strand: 'SO_DAI_SO', topic: 'Phương trình bậc hai', name: 'Công thức nghiệm', formula: '$x_{1,2}=\\f{-b\\pm\\s{\\Delta}}{2a}$ với $\\Delta=b^{2}-4ac$', condition: '$a\\ne0$, $\\Delta\\ge0$', usage: 'Giải phương trình bậc hai.', trap: 'Quên kiểm tra $a\\ne0$ khi có tham số.' },
  { id: 'f9-4', grade: 9, strand: 'SO_DAI_SO', topic: 'Viète', name: 'Hệ thức Viète', formula: '$S=x_1+x_2=-\\f{b}{a}$ ; $P=x_1x_2=\\f{c}{a}$', condition: 'Phương trình có nghiệm ($\\Delta\\ge0$)', usage: 'Tính biểu thức đối xứng, bài toán tham số.', trap: 'Dùng Viète mà chưa kiểm tra $\\Delta\\ge0$.' },
  { id: 'f9-5', grade: 9, strand: 'SO_DAI_SO', topic: 'Viète', name: 'Biểu thức đối xứng thường gặp', formula: '$x_1^{2}+x_2^{2}=S^{2}-2P$ ; $(x_1-x_2)^{2}=S^{2}-4P$ ; $x_1^{3}+x_2^{3}=S^{3}-3PS$', usage: 'Câu phân loại thi vào 10.', trap: 'Nhớ nhầm $S^{2}-4P$ thành $S^{2}-2P$.' },
  { id: 'f9-6', grade: 9, strand: 'SO_DAI_SO', topic: 'Viète', name: 'Dấu của hai nghiệm', formula: 'Trái dấu $\\Leftrightarrow P<0$ ; Cùng dương $\\Leftrightarrow\\Delta\\ge0$, $S>0$, $P>0$', usage: 'Bài toán tham số về dấu nghiệm.', trap: 'Trái dấu thì không cần điều kiện $\\Delta$ (tự động $\\Delta>0$).' },
  { id: 'f9-7', grade: 9, strand: 'SO_DAI_SO', topic: 'Nhẩm nghiệm', name: 'Nhẩm nghiệm nhanh', formula: '$a+b+c=0\\Rightarrow x_1=1,\\ x_2=\\f{c}{a}$ ; $a-b+c=0\\Rightarrow x_1=-1,\\ x_2=-\\f{c}{a}$', usage: 'Tiết kiệm thời gian trong phòng thi.', trap: 'Chỉ dùng khi kiểm tra đúng tổng hệ số.' },
  { id: 'f9-8', grade: 9, strand: 'HINH_HOC', topic: 'Hệ thức lượng', name: 'Hệ thức về cạnh và đường cao', formula: '$b^{2}=ab\'$ ; $c^{2}=ac\'$ ; $h^{2}=b\'c\'$ ; $ah=bc$ ; $\\f{1}{h^{2}}=\\f{1}{b^{2}}+\\f{1}{c^{2}}$', condition: 'Tam giác vuông có đường cao ứng với cạnh huyền', usage: 'Tính cạnh, đường cao, hình chiếu.', trap: 'Nhầm hình chiếu của cạnh này với cạnh kia.' },
  { id: 'f9-9', grade: 9, strand: 'HINH_HOC', topic: 'Lượng giác', name: 'Hệ thức lượng giác cơ bản', formula: '$\\sin^{2}\\alpha+\\cos^{2}\\alpha=1$ ; $\\tan\\alpha=\\f{\\sin\\alpha}{\\cos\\alpha}$ ; $\\tan\\alpha\\cot\\alpha=1$', usage: 'Tính tỉ số lượng giác còn lại.', trap: 'Với góc nhọn mọi tỉ số đều dương.' },
  { id: 'f9-10', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Góc nội tiếp', formula: 'Góc nội tiếp $=\\f{1}{2}$ số đo cung bị chắn', usage: 'Chuyển góc thành cung và ngược lại.', trap: 'Góc ở tâm bằng cả cung, không phải nửa cung.' },
  { id: 'f9-11', grade: 9, strand: 'HINH_HOC', topic: 'Tứ giác nội tiếp', name: 'Dấu hiệu tứ giác nội tiếp', formula: 'Tổng hai góc đối $=180\\deg$ ; hai đỉnh kề cùng nhìn một cạnh dưới hai góc bằng nhau', usage: 'Ý a của câu hình thi vào 10.', trap: 'Phải chỉ rõ hai góc **đối** nhau.' },
  { id: 'f9-12', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Độ dài cung và diện tích quạt', formula: '$l=\\f{\\pi Rn}{180}$ ; $S_{quat}=\\f{\\pi R^{2}n}{360}=\\f{lR}{2}$', condition: '$n$ tính bằng độ', usage: 'Tính độ dài cung, diện tích hình quạt.', trap: 'Nhầm mẫu 180 và 360.' },
  { id: 'f9-13', grade: 9, strand: 'HINH_HOC', topic: 'Hình khối tròn xoay', name: 'Hình nón và hình cầu', formula: '$S_{xq}^{non}=\\pi rl$ ; $V^{non}=\\f{1}{3}\\pi r^{2}h$ ; $S^{cau}=4\\pi R^{2}$ ; $V^{cau}=\\f{4}{3}\\pi R^{3}$', usage: 'Bài toán hình khối tròn xoay.', trap: 'Phân biệt đường sinh $l$ và chiều cao $h$: $l^{2}=r^{2}+h^{2}$.' },
];
