import type { FormulaCard } from '@/types';

/* MATHGITA — CẨM NANG CÔNG THỨC ĐIỂM 10 (bổ sung) */

export const FORMULAS_PLUS: FormulaCard[] = [
  /* ------------------------------ LỚP 6 ------------------------------ */
  { id: 'f6-13', grade: 6, strand: 'SO_DAI_SO', topic: 'Tính nhanh', name: 'Cặp số tròn cần thuộc', formula: '$25\\cdot4=100$ ; $125\\cdot8=1000$ ; $50\\cdot2=100$ ; $5\\cdot2=10$', usage: 'Tách thừa số để tạo số tròn khi tính nhanh.', trap: 'Tách xong phải kiểm tra tích còn đúng bằng số ban đầu.' },
  { id: 'f6-14', grade: 6, strand: 'SO_DAI_SO', topic: 'Dãy số', name: 'Tổng dãy số cách đều', formula: '$S=\\f{(\\text{đầu}+\\text{cuối})\\cdot n}{2}$ với $n=\\f{\\text{cuối}-\\text{đầu}}{d}+1$', usage: 'Tính tổng $1+2+\\dots+n$ hoặc dãy cách đều bất kỳ.', trap: 'Quên cộng 1 khi đếm số số hạng.' },
  { id: 'f6-15', grade: 6, strand: 'SO_DAI_SO', topic: 'Lũy thừa', name: 'Tổng các lũy thừa liên tiếp', formula: '$S=1+a+a^{2}+\\dots+a^{n}\\Rightarrow S=\\f{a^{n+1}-1}{a-1}$', condition: '$a\\ne1$', usage: 'Tính tổng dãy lũy thừa, chứng minh chia hết.', trap: 'Cách làm gốc: nhân $S$ với $a$ rồi trừ theo vế.' },
  { id: 'f6-16', grade: 6, strand: 'SO_DAI_SO', topic: 'Số nguyên', name: 'Quy tắc dấu của tích', formula: 'Chẵn thừa số âm $\\to$ tích dương ; lẻ thừa số âm $\\to$ tích âm', usage: 'Xác định dấu trước khi nhân các giá trị tuyệt đối.', trap: '$(-2)^{4}=16$ nhưng $-2^{4}=-16$ — dấu ngoặc quyết định.' },
  { id: 'f6-17', grade: 6, strand: 'SO_DAI_SO', topic: 'Phân số', name: 'So sánh phân số', formula: 'Cùng mẫu: so tử. Cùng tử: mẫu nhỏ hơn thì lớn hơn. Khác cả hai: quy đồng hoặc so với 1.', usage: 'Sắp thứ tự nhiều phân số.', trap: 'Với phân số âm, mọi so sánh đảo chiều.' },
  { id: 'f6-18', grade: 6, strand: 'HINH_HOC', topic: 'Đơn vị đo', name: 'Đổi đơn vị diện tích và thể tích', formula: '$1\\,m=100\\,cm$ nhưng $1\\,m^{2}=10\\,000\\,cm^{2}$ và $1\\,m^{3}=1\\,000\\,000\\,cm^{3}$', usage: 'Bài toán lát gạch, sơn tường, bể nước.', trap: 'Đổi đơn vị theo bậc 1 cho diện tích — lỗi mất điểm số 1.' },
  { id: 'f6-19', grade: 6, strand: 'HINH_HOC', topic: 'Đơn vị đo', name: 'Đơn vị dung tích', formula: '$1\\,dm^{3}=1$ lít $=1000\\,cm^{3}$ ; $1\\,m^{3}=1000$ lít', usage: 'Bài toán bể nước, thùng chứa.', trap: 'Nhớ dùng chiều cao **cột nước**, không phải chiều cao bể.' },
  { id: 'f6-20', grade: 6, strand: 'HINH_HOC', topic: 'Góc', name: 'Hệ thức cộng góc', formula: 'Tia $Oy$ nằm giữa $Ox$, $Oz$ $\\Rightarrow\\angle xOy+\\angle yOz=\\angle xOz$', usage: 'Tính số đo góc, chứng minh tia phân giác.', trap: 'Phải lập luận tia nằm giữa trước khi dùng hệ thức.' },
  { id: 'f6-21', grade: 6, strand: 'THONG_KE_XS', topic: 'Xác suất', name: 'Xác suất thực nghiệm', formula: '$P=\\f{\\text{số lần biến cố xảy ra}}{\\text{tổng số lần thực hiện}}$', condition: '$0\\le P\\le1$', usage: 'Trò chơi gieo xúc xắc, tung đồng xu.', trap: 'Kết quả phải nằm trong đoạn từ 0 đến 1 — nếu vượt thì đã tính sai.' },

  /* ------------------------------ LỚP 7 ------------------------------ */
  { id: 'f7-10', grade: 7, strand: 'SO_DAI_SO', topic: 'Lũy thừa', name: 'Lũy thừa của một thương', formula: '$\\left(\\f{x}{y}\\right)^{n}=\\f{x^{n}}{y^{n}}$', condition: '$y\\ne0$', usage: 'Rút gọn biểu thức có phân số mũ.', trap: 'Không áp dụng được cho tổng: $(x+y)^{n}\\ne x^{n}+y^{n}$.' },
  { id: 'f7-11', grade: 7, strand: 'SO_DAI_SO', topic: 'Số thực', name: 'Căn bậc hai số học', formula: '$\\s{a}=b\\Leftrightarrow b\\ge0$ và $b^{2}=a$', condition: '$a\\ge0$', usage: 'Tính giá trị căn, giải phương trình đơn giản.', trap: '$\\s{9}=3$ (một giá trị) nhưng $x^{2}=9\\Rightarrow x=\\pm3$ (hai giá trị).' },
  { id: 'f7-12', grade: 7, strand: 'SO_DAI_SO', topic: 'Tỉ lệ thức', name: 'Dãy tỉ số bằng nhau có hệ số', formula: '$\\f{a}{b}=\\f{c}{d}=\\f{ma+nc}{mb+nd}$', condition: '$mb+nd\\ne0$', usage: 'Khi đề cho tổng/hiệu có hệ số, ví dụ $2a+3c=k$.', trap: 'Chọn $m$, $n$ sao cho tử số khớp đúng dữ kiện đề cho.' },
  { id: 'f7-13', grade: 7, strand: 'SO_DAI_SO', topic: 'Đa thức', name: 'Định lí Bézout (lớp 7 - 8)', formula: '$P(x)$ chia hết cho $(x-a)\\Leftrightarrow P(a)=0$', usage: 'Tìm tham số để đa thức chia hết, xác định nghiệm.', trap: 'Dùng thay cho phép chia dài — nhanh hơn nhiều lần.' },
  { id: 'f7-14', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Góc ngoài của tam giác', formula: 'Góc ngoài tại một đỉnh $=$ tổng hai góc trong không kề với nó', usage: 'Tính góc nhanh mà không cần tính góc trong tương ứng.', trap: 'Phải lấy hai góc **không kề**, không phải hai góc bất kỳ.' },
  { id: 'f7-15', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Bốn trường hợp bằng nhau của tam giác vuông', formula: 'Hai cạnh góc vuông ; Cạnh góc vuông – góc nhọn kề ; Cạnh huyền – góc nhọn ; Cạnh huyền – cạnh góc vuông', usage: 'Chứng minh hai tam giác vuông bằng nhau.', trap: 'Trường hợp cạnh huyền – cạnh góc vuông chỉ đúng cho tam giác vuông.' },
  { id: 'f7-16', grade: 7, strand: 'HINH_HOC', topic: 'Đường trung trực', name: 'Tính chất điểm thuộc trung trực', formula: '$M$ thuộc trung trực của $AB\\Leftrightarrow MA=MB$', usage: 'Chứng minh cách đều, chứng minh thuộc trung trực.', trap: 'Đây là điều kiện cần và đủ — dùng được theo cả hai chiều.' },
  { id: 'f7-17', grade: 7, strand: 'THONG_KE_XS', topic: 'Xác suất', name: 'Xác suất trong mô hình đồng khả năng', formula: '$P(A)=\\f{m}{k}$ với $m$ là số kết quả thuận lợi, $k$ là tổng số kết quả', usage: 'Rút thẻ, gieo xúc xắc, tung đồng xu.', trap: 'Chỉ dùng khi các kết quả **đồng khả năng**.' },

  /* ------------------------------ LỚP 8 ------------------------------ */
  { id: 'f8-11', grade: 8, strand: 'SO_DAI_SO', topic: 'Hằng đẳng thức', name: 'Bình phương của một hiệu', formula: '$(A-B)^{2}=A^{2}-2AB+B^{2}$', usage: 'Khai triển, hoàn thành bình phương, tính nhanh.', trap: 'Hạng tử giữa mang dấu trừ, hai hạng tử ngoài luôn dương.' },
  { id: 'f8-12', grade: 8, strand: 'SO_DAI_SO', topic: 'Hằng đẳng thức', name: 'Lập phương của một tổng', formula: '$(A+B)^{3}=A^{3}+3A^{2}B+3AB^{2}+B^{3}$', usage: 'Khai triển bậc ba, phân tích nhân tử.', trap: 'Hệ số là $1;3;3;1$ — dễ nhầm thành $1;2;2;1$.' },
  { id: 'f8-13', grade: 8, strand: 'SO_DAI_SO', topic: 'Nhân tử', name: 'Tách hạng tử cho tam thức', formula: '$ax^{2}+bx+c$: tìm hai số có tích $ac$ và tổng $b$', usage: 'Phân tích tam thức bậc hai thành nhân tử.', trap: 'Khi $a\\ne1$ phải lấy tích $ac$, không phải $c$.' },
  { id: 'f8-14', grade: 8, strand: 'SO_DAI_SO', topic: 'Nhân tử', name: 'Hằng đẳng thức Sophie Germain', formula: '$x^{4}+4y^{4}=(x^{2}-2xy+2y^{2})(x^{2}+2xy+2y^{2})$', usage: 'Đề học sinh giỏi, phân tích $x^{4}+4$.', trap: 'Kỹ thuật gốc: thêm và bớt $4x^{2}y^{2}$.' },
  { id: 'f8-15', grade: 8, strand: 'SO_DAI_SO', topic: 'Chuyển động', name: 'Công thức chuyển động', formula: '$s=v\\cdot t$ ; xuôi dòng $v+v_{n}$ ; ngược dòng $v-v_{n}$', usage: 'Bài toán lập phương trình về chuyển động.', trap: 'Đổi phút sang giờ trước khi thay vào công thức.' },
  { id: 'f8-16', grade: 8, strand: 'SO_DAI_SO', topic: 'Số học', name: 'Biểu diễn số có hai, ba chữ số', formula: '$\\ov{ab}=10a+b$ ; $\\ov{abc}=100a+10b+c$', condition: '$1\\le a\\le9$, $0\\le b,c\\le9$', usage: 'Bài toán tìm số khi đổi chỗ chữ số.', trap: 'Nhớ điều kiện chữ số đầu khác 0.' },
  { id: 'f8-17', grade: 8, strand: 'HINH_HOC', topic: 'Đường trung bình', name: 'Đường trung bình của tam giác và hình thang', formula: 'Tam giác: $MN\\para BC$, $MN=\\f{BC}{2}$. Hình thang: $MN\\para$ hai đáy, $MN=\\f{a+b}{2}$', usage: 'Chứng minh song song, tính độ dài.', trap: 'Phải nối trung điểm **hai cạnh** mới là đường trung bình.' },
  { id: 'f8-18', grade: 8, strand: 'HINH_HOC', topic: 'Tứ giác', name: 'Trung tuyến ứng với cạnh huyền', formula: 'Tam giác vuông tại $A$, $M$ là trung điểm $BC$ $\\Rightarrow AM=\\f{BC}{2}=MB=MC$', usage: 'Cho ngay ba đoạn bằng nhau — rất mạnh khi chứng minh.', trap: 'Chiều ngược lại cũng đúng: nếu $AM=\\f{BC}{2}$ thì tam giác vuông tại $A$.' },
  { id: 'f8-19', grade: 8, strand: 'HINH_HOC', topic: 'Đồng dạng', name: 'Ba trường hợp đồng dạng', formula: 'c.c.c (ba cạnh tỉ lệ) ; c.g.c (hai cạnh tỉ lệ, góc xen giữa bằng nhau) ; g.g (hai góc bằng nhau)', usage: 'g.g là trường hợp nhẹ điều kiện nhất, dùng nhiều nhất.', trap: 'Viết đúng thứ tự đỉnh tương ứng khi ký hiệu $\\sim$.' },
  { id: 'f8-20', grade: 8, strand: 'HINH_HOC', topic: 'Hình chóp', name: 'Hình chóp đều', formula: '$S_{xq}=p\\cdot d$ ($p$ là nửa chu vi đáy, $d$ là trung đoạn) ; $V=\\f{1}{3}S_{\\text{đáy}}\\cdot h$', usage: 'Bài toán mô hình kim tự tháp, lều trại.', trap: 'Phân biệt trung đoạn $d$ (trên mặt bên) với chiều cao $h$ (trong khối).' },

  /* ------------------------------ LỚP 9 ------------------------------ */
  { id: 'f9-14', grade: 9, strand: 'SO_DAI_SO', topic: 'Căn thức', name: 'Đưa thừa số ra ngoài dấu căn', formula: '$\\s{A^{2}B}=\\abs{A}\\s{B}$', condition: '$B\\ge0$', usage: 'Rút gọn căn, cộng trừ các căn đồng dạng.', trap: 'Giữ dấu giá trị tuyệt đối khi chưa biết dấu của $A$.' },
  { id: 'f9-15', grade: 9, strand: 'SO_DAI_SO', topic: 'Căn thức', name: 'Rút gọn căn kép', formula: '$a\\pm2\\s{b}=(\\s{m}\\pm\\s{n})^{2}$ với $m+n=a$, $mn=b$', usage: 'Rút gọn $\\s{7+4\\s{3}}$ và các biểu thức tương tự.', trap: 'Kết quả phải không âm — nhớ xét dấu trước khi bỏ giá trị tuyệt đối.' },
  { id: 'f9-16', grade: 9, strand: 'SO_DAI_SO', topic: 'Hệ phương trình', name: 'Số nghiệm của hệ hai phương trình', formula: 'Nghiệm duy nhất $\\Leftrightarrow ab\'-a\'b\\ne0$ ; vô nghiệm hoặc vô số nghiệm khi $ab\'-a\'b=0$', usage: 'Bài toán tham số về hệ phương trình.', trap: 'Dùng $ab\'-a\'b$ thay cho tỉ số để tránh chia cho 0.' },
  { id: 'f9-17', grade: 9, strand: 'SO_DAI_SO', topic: 'Phương trình bậc hai', name: 'Công thức nghiệm thu gọn', formula: 'Với $b=2b\'$: $\\Delta\'=b\'^{2}-ac$ ; $x_{1,2}=\\f{-b\'\\pm\\s{\\Delta\'}}{a}$', usage: 'Khi hệ số $b$ chẵn — tính nhanh và số nhỏ hơn.', trap: 'Nhớ dùng $b\'=\\f{b}{2}$, không phải $b$.' },
  { id: 'f9-18', grade: 9, strand: 'SO_DAI_SO', topic: 'Viète', name: 'Nhẩm hai số biết tổng và tích', formula: 'Hai số có tổng $S$ và tích $P$ là nghiệm của $X^{2}-SX+P=0$', condition: '$S^{2}-4P\\ge0$', usage: 'Bài toán tìm hai số, lập phương trình bậc hai từ hai nghiệm.', trap: 'Dấu trong phương trình là $-S$ và $+P$.' },
  { id: 'f9-19', grade: 9, strand: 'SO_DAI_SO', topic: 'Phương trình', name: 'Phương trình trùng phương', formula: '$ax^{4}+bx^{2}+c=0$: đặt $t=x^{2}\\ge0$ rồi giải theo $t$', usage: 'Giải phương trình bậc bốn dạng đặc biệt.', trap: 'Loại nghiệm $t<0$ trước khi quay về $x$; mỗi $t>0$ cho hai giá trị $x=\\pm\\s{t}$.' },
  { id: 'f9-20', grade: 9, strand: 'SO_DAI_SO', topic: 'Bất đẳng thức', name: 'Bất đẳng thức Cô-si (AM–GM)', formula: '$a+b\\ge2\\s{ab}$ ; $a+b+c\\ge3\\cb{abc}$', condition: '$a,b,c\\ge0$; dấu “=” khi các số bằng nhau', usage: 'Tìm giá trị nhỏ nhất của tổng khi tích là hằng số.', trap: 'Luôn nêu điều kiện không âm trước khi áp dụng.' },
  { id: 'f9-21', grade: 9, strand: 'SO_DAI_SO', topic: 'Bất đẳng thức', name: 'Hệ quả Cô-si thường dùng', formula: '$x+\\f{1}{x}\\ge2$ với $x>0$ ; $\\f{a}{b}+\\f{b}{a}\\ge2$ với $a,b$ cùng dấu', usage: 'Cực trị biểu thức phân thức.', trap: 'Với $x<0$ thì bất đẳng thức đảo chiều: $x+\\f{1}{x}\\le-2$.' },
  { id: 'f9-22', grade: 9, strand: 'HINH_HOC', topic: 'Lượng giác', name: 'Giá trị lượng giác góc đặc biệt', formula: '$\\sin30\\deg=\\f{1}{2}$ ; $\\sin45\\deg=\\f{\\s{2}}{2}$ ; $\\sin60\\deg=\\f{\\s{3}}{2}$ ; $\\tan45\\deg=1$', usage: 'Tính nhanh trong tam giác vuông có góc đặc biệt.', trap: '$\\cos$ đọc ngược lại: $\\cos30\\deg=\\f{\\s{3}}{2}$, $\\cos60\\deg=\\f{1}{2}$.' },
  { id: 'f9-23', grade: 9, strand: 'HINH_HOC', topic: 'Lượng giác', name: 'Góc phụ nhau', formula: 'Nếu $\\alpha+\\beta=90\\deg$ thì $\\sin\\alpha=\\cos\\beta$ ; $\\tan\\alpha=\\cot\\beta$', usage: 'Rút gọn biểu thức lượng giác, so sánh tỉ số.', trap: 'Chỉ đúng khi hai góc phụ nhau, không phải bù nhau.' },
  { id: 'f9-24', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Hai tiếp tuyến cắt nhau', formula: '$MA=MB$ ; $MO$ là phân giác $\\angle AMB$ và $\\angle AOB$ ; $MO\\perp AB$ tại trung điểm $AB$', usage: 'Một giả thiết cho bốn kết luận — khai thác triệt để.', trap: 'Đừng chỉ dùng $MA=MB$ mà bỏ quên ba kết luận còn lại.' },
  { id: 'f9-25', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Phương tích của một điểm', formula: '$MA\\cdot MB=MC\\cdot MD=MT^{2}$', condition: '$MT$ là tiếp tuyến, $MAB$ và $MCD$ là cát tuyến', usage: 'Chứng minh hệ thức tích, ý c–d của câu hình thi vào 10.', trap: 'Chứng minh bằng hai tam giác đồng dạng (góc tiếp tuyến – dây).' },
  { id: 'f9-26', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Góc có đỉnh trong và ngoài đường tròn', formula: 'Đỉnh bên trong: $\\f{1}{2}$(tổng hai cung bị chắn). Đỉnh bên ngoài: $\\f{1}{2}$(hiệu hai cung bị chắn)', usage: 'Tính góc trong các cấu hình cát tuyến.', trap: 'Bên trong lấy tổng, bên ngoài lấy hiệu — rất dễ nhầm.' },
  { id: 'f9-27', grade: 9, strand: 'HINH_HOC', topic: 'Hình khối', name: 'Liên hệ trong hình nón', formula: '$l^{2}=r^{2}+h^{2}$', usage: 'Tìm chiều cao khi biết bán kính và đường sinh.', trap: 'Đường sinh $l$ luôn là cạnh lớn nhất trong tam giác vuông đó.' },
  { id: 'f9-28', grade: 9, strand: 'THONG_KE_XS', topic: 'Thống kê', name: 'Tần số tương đối', formula: '$f_i=\\f{n_i}{N}\\cdot100\\percent$ ; $\\sum f_i=100\\percent$', usage: 'Lập bảng tần số tương đối, vẽ biểu đồ quạt tròn.', trap: 'Kiểm tra tổng các tần số tương đối phải bằng 100%.' },
];
