import type { FormulaCard } from '@/types';

/* =====================================================================
   MATHGITA — CẨM NANG CÔNG THỨC ĐIỂM 10 (BỘ ĐẦY ĐỦ)
   Rà soát cho thấy nhiều chủ đề mới chỉ có một thẻ công thức, trong khi
   chuẩn GITA yêu cầu mỗi chuyên đề phải có đủ bộ công thức trọng tâm.
   File này bổ sung phần còn thiếu; mỗi thẻ luôn có ba phần: **công thức**,
   **dùng khi nào**, và **bẫy thường gặp** — đúng cấu trúc thẻ ghi nhớ.
   ===================================================================== */

export const FORMULAS_FULL: FormulaCard[] = [
  /* ============================== LỚP 6 ============================== */
  { id: 'f6-22', grade: 6, strand: 'SO_DAI_SO', topic: 'Thứ tự phép tính', name: 'Thứ tự thực hiện phép tính', formula: 'Ngoặc $\\to$ Luỹ thừa $\\to$ Nhân, chia $\\to$ Cộng, trừ', usage: 'Mọi biểu thức số nhiều phép tính.', trap: 'Nhân chia (và cộng trừ) làm từ **trái sang phải**, không phải nhân trước chia sau.' },
  { id: 'f6-23', grade: 6, strand: 'SO_DAI_SO', topic: 'Thứ tự phép tính', name: 'Thứ tự mở ngoặc', formula: 'Tròn $(\\;)$ $\\to$ Vuông $[\\;]$ $\\to$ Nhọn $\\{\\;\\}$', usage: 'Biểu thức có nhiều tầng ngoặc.', trap: 'Bỏ dấu ngoặc có dấu trừ đằng trước thì **đổi dấu tất cả** hạng tử bên trong.' },
  { id: 'f6-24', grade: 6, strand: 'SO_DAI_SO', topic: 'Số tự nhiên', name: 'Đếm số phần tử của dãy cách đều', formula: '$n=\\f{\\text{cuối}-\\text{đầu}}{d}+1$', usage: 'Đếm số số hạng, số phần tử của tập hợp cho bằng khoảng.', trap: 'Quên **cộng 1** ở cuối là lỗi phổ biến nhất.' },
  { id: 'f6-25', grade: 6, strand: 'SO_DAI_SO', topic: 'Phép chia', name: 'Phép chia có dư', formula: '$a=b\\cdot q+r$', condition: '$0\\le r<b$', usage: 'Bài toán chia dư, tìm số bị chia hoặc số chia.', trap: 'Số dư luôn **nhỏ hơn số chia** và không âm — kiểm tra lại nếu $r\\ge b$.' },
  { id: 'f6-26', grade: 6, strand: 'SO_DAI_SO', topic: 'Tính chia hết', name: 'Dấu hiệu chia hết cơ bản', formula: '$2$, $5$: xét **chữ số tận cùng** · $3$, $9$: xét **tổng các chữ số** · $4$, $25$: xét **hai chữ số cuối**', usage: 'Kiểm tra nhanh một số có chia hết hay không.', trap: 'Dùng nhầm dấu hiệu: chia hết cho $9$ thì xét tổng chữ số, không xét chữ số cuối.' },
  { id: 'f6-27', grade: 6, strand: 'SO_DAI_SO', topic: 'ƯCLN – BCNN', name: 'Quan hệ giữa ƯCLN và BCNN', formula: '$\\text{ƯCLN}(a;b)\\cdot\\text{BCNN}(a;b)=a\\cdot b$', usage: 'Biết một trong hai, tính đại lượng còn lại; kiểm tra kết quả.', trap: 'BCNN chỉ bằng $a\\cdot b$ khi hai số **nguyên tố cùng nhau**.' },
  { id: 'f6-28', grade: 6, strand: 'SO_DAI_SO', topic: 'ƯCLN – BCNN', name: 'Nhận dạng bài toán ƯCLN hay BCNN', formula: 'Chia đều, "**nhiều nhất**" $\\to$ ƯCLN · Lặp lại, gặp nhau, "**ít nhất**" $\\to$ BCNN', usage: 'Bài toán thực tế về chia quà, xe buýt, đèn nháy.', trap: 'Khoanh từ khoá "nhiều nhất" / "ít nhất" ngay khi đọc đề.' },
  { id: 'f6-29', grade: 6, strand: 'SO_DAI_SO', topic: 'ƯCLN – BCNN', name: 'Dạng chia dư và chia thiếu', formula: 'Chia $a$, $b$ **đều dư $r$** $\\to n=\\text{BCNN}\\cdot k+r$ · **đều thiếu $t$** $\\to n=\\text{BCNN}\\cdot k-t$', usage: 'Tìm số thoả nhiều điều kiện chia dư cùng lúc.', trap: '"Thiếu" thì **trừ**, không phải cộng — hai dạng ngược chiều nhau.' },
  { id: 'f6-30', grade: 6, strand: 'SO_DAI_SO', topic: 'Số nguyên', name: 'Số đối và giá trị tuyệt đối', formula: 'Số đối của $a$ là $-a$ · $|a|\\ge0$ với mọi $a$ · $|a|=|-a|$', usage: 'Tính toán với số nguyên, giải phương trình chứa dấu giá trị tuyệt đối.', trap: 'Số đối (đổi dấu) khác số nghịch đảo (lật tử mẫu).' },
  { id: 'f6-31', grade: 6, strand: 'SO_DAI_SO', topic: 'Số nguyên', name: 'Quy tắc dấu ngoặc và chuyển vế', formula: 'Bỏ ngoặc sau dấu $-$: đổi dấu mọi hạng tử · Chuyển vế: đổi dấu hạng tử chuyển', usage: 'Rút gọn biểu thức, tìm $x$.', trap: 'Chỉ đổi dấu hạng tử **đầu tiên** trong ngoặc là lỗi kinh điển.' },
  { id: 'f6-32', grade: 6, strand: 'SO_DAI_SO', topic: 'Phân số', name: 'Hỗn số và phân số', formula: '$a\\f{b}{c}=\\f{a\\cdot c+b}{c}$', condition: '$c\\ne0$', usage: 'Đổi hỗn số sang phân số trước khi tính toán.', trap: 'Với hỗn số âm: $-a\\f{b}{c}=-\\f{a\\cdot c+b}{c}$, dấu trừ áp cho **cả** hỗn số.' },
  { id: 'f6-33', grade: 6, strand: 'SO_DAI_SO', topic: 'Phân số', name: 'Bốn phép tính với phân số', formula: '$\\f{a}{b}\\pm\\f{c}{d}=\\f{ad\\pm bc}{bd}$ · $\\f{a}{b}\\cdot\\f{c}{d}=\\f{ac}{bd}$ · $\\f{a}{b}:\\f{c}{d}=\\f{a}{b}\\cdot\\f{d}{c}$', condition: '$b,d\\ne0$; phép chia cần $c\\ne0$', usage: 'Mọi bài tính giá trị biểu thức phân số.', trap: 'Cộng trừ phải quy đồng; nhân chia thì **không** cần quy đồng.' },
  { id: 'f6-34', grade: 6, strand: 'SO_DAI_SO', topic: 'Phân số', name: 'Tách sai phân', formula: '$\\f{1}{n(n+1)}=\\f{1}{n}-\\f{1}{n+1}$ · tổng quát $\\f{k}{n(n+k)}=\\f{1}{n}-\\f{1}{n+k}$', usage: 'Tính tổng dãy phân số có quy luật.', trap: 'Sau khi tách, các hạng tử giữa triệt tiêu, chỉ còn hai đầu.' },
  { id: 'f6-35', grade: 6, strand: 'SO_DAI_SO', topic: 'Tỉ số phần trăm', name: 'Ba bài toán về tỉ số phần trăm', formula: 'Tìm $\\f{a}{b}$ của $x$: lấy $x\\cdot\\f{a}{b}$ · Tìm $x$ biết $\\f{a}{b}$ của nó bằng $c$: lấy $c:\\f{a}{b}$', usage: 'Bài toán thực tế về phần trăm, giảm giá, lãi suất.', trap: 'Đọc kỹ đâu là số **đã biết**, đâu là số **cần tìm** — hai dạng ngược nhau.' },
  { id: 'f6-36', grade: 6, strand: 'SO_DAI_SO', topic: 'Tỉ số phần trăm', name: 'Tăng giảm liên tiếp', formula: 'Tăng $a\\%$: nhân $\\left(1+\\f{a}{100}\\right)$ · Giảm $b\\%$: nhân $\\left(1-\\f{b}{100}\\right)$', usage: 'Bài toán giá cả tăng rồi giảm (hoặc ngược lại).', trap: 'Tăng $10\\%$ rồi giảm $10\\%$ **không** trở về giá cũ, vì mốc tính đã đổi.' },
  { id: 'f6-37', grade: 6, strand: 'HINH_HOC', topic: 'Chu vi', name: 'Chu vi các hình cơ bản', formula: 'Chữ nhật $2(a+b)$ · Vuông $4a$ · Tam giác $a+b+c$ · Hình thoi $4a$', usage: 'Bài toán hàng rào, viền khung, nẹp.', trap: 'Hàng rào dùng **chu vi**; lát gạch, sơn dùng **diện tích**.' },
  { id: 'f6-38', grade: 6, strand: 'HINH_HOC', topic: 'Diện tích', name: 'Diện tích các hình cơ bản', formula: 'Chữ nhật $ab$ · Vuông $a^{2}$ · Tam giác $\\f{ah}{2}$ · Hình thang $\\f{(a+b)h}{2}$ · Hình thoi $\\f{d_1d_2}{2}$ · Bình hành $ah$', usage: 'Bài toán diện tích đất, lát nền, sơn tường.', trap: 'Hình thoi dùng **nửa tích hai đường chéo**, không phải tích.' },
  { id: 'f6-39', grade: 6, strand: 'HINH_HOC', topic: 'Đối xứng', name: 'Số trục đối xứng của các hình', formula: 'Vuông $4$ · Chữ nhật $2$ · Thoi $2$ · Tam giác đều $3$ · Lục giác đều $6$ · Bình hành $0$', usage: 'Câu nhận biết về tính đối xứng.', trap: 'Đường chéo hình chữ nhật **không** phải trục đối xứng.' },
  { id: 'f6-40', grade: 6, strand: 'HINH_HOC', topic: 'Đối xứng', name: 'Hình có tâm đối xứng', formula: 'Có tâm: hình vuông, chữ nhật, thoi, bình hành, lục giác đều · **Không** có tâm: tam giác đều, hình thang cân', usage: 'Phân biệt trục đối xứng với tâm đối xứng.', trap: 'Tam giác đều có $3$ trục nhưng không có tâm đối xứng.' },
  { id: 'f6-41', grade: 6, strand: 'HINH_HOC', topic: 'Đoạn thẳng', name: 'Trung điểm của đoạn thẳng', formula: '$M$ là trung điểm $AB\\Leftrightarrow M$ nằm giữa $A$, $B$ **và** $MA=MB=\\f{AB}{2}$', usage: 'Chứng minh trung điểm, tính độ dài.', trap: 'Cần **cả hai** điều kiện; chỉ $MA=MB$ thì $M$ có thể nằm ngoài đoạn.' },
  { id: 'f6-42', grade: 6, strand: 'HINH_HOC', topic: 'Đếm hình', name: 'Công thức "chọn 2 trong n"', formula: 'Số đoạn thẳng từ $n$ điểm $=$ số góc từ $n$ tia chung gốc $=\\f{n(n-1)}{2}$', usage: 'Bài toán đếm đoạn thẳng, góc, giao điểm.', trap: 'Nhớ **chia 2** vì mỗi hình bị đếm hai lần.' },
  { id: 'f6-43', grade: 6, strand: 'THONG_KE_XS', topic: 'Thống kê', name: 'Số trung bình, mốt và trung vị', formula: 'Trung bình $=\\f{\\text{tổng}}{\\text{số giá trị}}$ · Mốt $=$ giá trị có tần số lớn nhất · Trung vị $=$ giá trị ở giữa khi sắp thứ tự', usage: 'Mô tả đặc trưng của một bộ số liệu.', trap: 'Số liệu có giá trị bất thường thì nên dùng **trung vị** thay cho trung bình.' },

  /* ============================== LỚP 7 ============================== */
  { id: 'f7-18', grade: 7, strand: 'SO_DAI_SO', topic: 'Số thực', name: 'Nhận biết thập phân hữu hạn', formula: 'Phân số **tối giản** có mẫu chỉ chứa ước nguyên tố $2$ và $5$ $\\Leftrightarrow$ viết được dạng thập phân hữu hạn', usage: 'Câu nhận biết về số thập phân.', trap: 'Phải rút gọn về tối giản **trước** khi xét mẫu.' },
  { id: 'f7-19', grade: 7, strand: 'SO_DAI_SO', topic: 'Số thực', name: 'Đổi thập phân tuần hoàn ra phân số', formula: '$0,(d)=\\f{d}{9}$ · $0,(\\ov{d_1d_2})=\\f{\\ov{d_1d_2}}{99}$', usage: 'Chuyển số thập phân vô hạn tuần hoàn sang phân số.', trap: 'Chu kỳ có mấy chữ số thì mẫu có bấy nhiêu chữ số $9$.' },
  { id: 'f7-20', grade: 7, strand: 'SO_DAI_SO', topic: 'Số thực', name: 'Căn bậc hai của bình phương', formula: '$\\s{A^{2}}=|A|$', usage: 'Rút gọn biểu thức chứa căn của một bình phương.', trap: 'Phải **xét dấu $A$** rồi mới bỏ dấu giá trị tuyệt đối.' },
  { id: 'f7-21', grade: 7, strand: 'SO_DAI_SO', topic: 'Giá trị tuyệt đối', name: 'Bất đẳng thức giá trị tuyệt đối', formula: '$|A|+|B|\\ge|A+B|$, dấu $=$ khi $A\\cdot B\\ge0$', usage: 'Tìm giá trị nhỏ nhất của tổng các giá trị tuyệt đối.', trap: 'Muốn triệt tiêu biến, phải **đổi dấu** một hạng tử: $|x-b|=|b-x|$.' },
  { id: 'f7-22', grade: 7, strand: 'SO_DAI_SO', topic: 'Giá trị tuyệt đối', name: 'Cực trị của tổng hai giá trị tuyệt đối', formula: '$|x-a|+|x-b|$ nhỏ nhất bằng $|a-b|$, đạt được khi $x$ nằm giữa $a$ và $b$', usage: 'Bài toán cực trị lớp 7 và thi HSG.', trap: 'Kết quả là một **khoảng** giá trị của $x$, không phải một điểm duy nhất.' },
  { id: 'f7-23', grade: 7, strand: 'SO_DAI_SO', topic: 'Đại lượng tỉ lệ', name: 'Phân biệt tỉ lệ thuận và nghịch', formula: 'Thuận: $y=kx$, **tỉ số** $\\f{y}{x}$ không đổi · Nghịch: $xy=a$, **tích** không đổi', usage: 'Nhận dạng bài toán, lập công thức liên hệ.', trap: 'Chia tỉ lệ nghịch với $a$, $b$ nghĩa là chia tỉ lệ thuận với $\\f{1}{a}$, $\\f{1}{b}$.' },
  { id: 'f7-24', grade: 7, strand: 'SO_DAI_SO', topic: 'Đa thức', name: 'Bậc, hệ số cao nhất, hệ số tự do', formula: 'Bậc $=$ số mũ lớn nhất · Hệ số cao nhất $=$ hệ số của hạng tử bậc cao nhất · Hệ số tự do $=$ hạng tử không chứa biến', usage: 'Câu nhận biết về đa thức một biến.', trap: 'Phải **thu gọn và sắp xếp** trước khi đọc các đại lượng này.' },
  { id: 'f7-25', grade: 7, strand: 'HINH_HOC', topic: 'Đường thẳng song song', name: 'Ba cặp góc khi có hai đường song song', formula: 'So le trong: **bằng nhau** · Đồng vị: **bằng nhau** · Trong cùng phía: **bù nhau**', usage: 'Tính góc, chứng minh hai đường thẳng song song.', trap: 'Gọi sai tên cặp góc là nguyên nhân của hầu hết lỗi sai chuyên đề này.' },
  { id: 'f7-26', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Bất đẳng thức tam giác', formula: '$|b-c|<a<b+c$ với mọi cạnh $a$', usage: 'Kiểm tra ba đoạn có tạo thành tam giác không; tìm miền giá trị của một cạnh.', trap: 'Chỉ cần kiểm tra tổng **hai cạnh nhỏ nhất** so với cạnh lớn nhất là đủ.' },
  { id: 'f7-27', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Quan hệ giữa góc và cạnh đối diện', formula: 'Trong một tam giác: cạnh lớn hơn $\\Leftrightarrow$ góc đối diện lớn hơn', usage: 'So sánh các cạnh, các góc trong tam giác.', trap: 'Quan hệ này chỉ đúng **trong cùng một tam giác**.' },
  { id: 'f7-28', grade: 7, strand: 'HINH_HOC', topic: 'Tam giác', name: 'Tam giác cân — bốn đường trùng nhau', formula: 'Trong tam giác cân, đường **phân giác** từ đỉnh đồng thời là trung tuyến, đường cao và trung trực của cạnh đáy', usage: 'Một dữ kiện suy ra bốn kết luận — rút ngắn rất nhiều bước.', trap: 'Chỉ đúng cho đường xuất phát từ **đỉnh cân**, không đúng cho hai đỉnh đáy.' },
  { id: 'f7-29', grade: 7, strand: 'HINH_HOC', topic: 'Đường đồng quy', name: 'Bốn điểm đặc biệt của tam giác', formula: 'Trung tuyến $\\to$ **trọng tâm** · Đường cao $\\to$ **trực tâm** · Phân giác $\\to$ tâm **nội** tiếp · Trung trực $\\to$ tâm **ngoại** tiếp', usage: 'Câu nhận biết và bài chứng minh đồng quy.', trap: 'Trọng tâm chia trung tuyến theo tỉ lệ $2:1$ tính từ đỉnh.' },
  { id: 'f7-30', grade: 7, strand: 'HINH_HOC', topic: 'Hình khối', name: 'Lăng trụ đứng và hình hộp', formula: '$S_{xq}=C_{\\text{đáy}}\\cdot h$ · $S_{tp}=S_{xq}+2S_{\\text{đáy}}$ · $V=S_{\\text{đáy}}\\cdot h$', usage: 'Bài toán hộp, thùng, bể chứa.', trap: 'Vật **không nắp** thì chỉ cộng **một** mặt đáy.' },
  { id: 'f7-31', grade: 7, strand: 'THONG_KE_XS', topic: 'Thống kê', name: 'Biểu đồ hình quạt tròn', formula: 'Tỉ lệ $=\\f{\\text{phần}}{\\text{tổng}}\\times100\\%$ · Góc ở tâm $=\\f{\\text{phần}}{\\text{tổng}}\\times360\\deg$', usage: 'Vẽ và đọc biểu đồ hình quạt tròn.', trap: 'Nhân $100$ cho phần trăm, nhân $360$ cho góc — đừng lẫn hai mốc.' },
  { id: 'f7-32', grade: 7, strand: 'THONG_KE_XS', topic: 'Thống kê', name: 'Tính mức tăng phần trăm', formula: 'Tăng $=\\f{\\text{giá trị mới}-\\text{giá trị cũ}}{\\text{giá trị cũ}}\\times100\\%$', usage: 'So sánh số liệu giữa hai thời điểm.', trap: 'Mẫu số luôn là giá trị **cũ** (mốc so sánh), không phải giá trị mới.' },

  /* ============================== LỚP 8 ============================== */
  { id: 'f8-21', grade: 8, strand: 'SO_DAI_SO', topic: 'Hằng đẳng thức', name: 'Lập phương của một tổng, một hiệu', formula: '$(a\\pm b)^{3}=a^{3}\\pm3a^{2}b+3ab^{2}\\pm b^{3}$', usage: 'Khai triển và thu gọn biểu thức bậc ba.', trap: 'Có **bốn** hạng tử; viết $(a+b)^{3}=a^{3}+b^{3}$ là sai hoàn toàn.' },
  { id: 'f8-22', grade: 8, strand: 'SO_DAI_SO', topic: 'Nhân tử', name: 'Tách hạng tử giữa', formula: 'Với $ax^{2}+bx+c$: tìm hai số có **tổng $b$**, **tích $ac$** rồi tách $bx$ thành hai phần', usage: 'Phân tích tam thức bậc hai thành nhân tử.', trap: 'Tích phải là $ac$ (không phải chỉ $c$) khi $a\\ne1$.' },
  { id: 'f8-23', grade: 8, strand: 'SO_DAI_SO', topic: 'Nhân tử', name: 'Đẳng thức Sophie Germain', formula: '$a^{4}+4b^{4}=(a^{2}-2ab+2b^{2})(a^{2}+2ab+2b^{2})$', usage: 'Phân tích $x^{4}+4$ và các dạng tương tự trong đề HSG.', trap: 'Cách dựng: thêm và bớt $4a^{2}b^{2}$ để tạo hiệu hai bình phương.' },
  { id: 'f8-24', grade: 8, strand: 'SO_DAI_SO', topic: 'Phân thức', name: 'Điều kiện xác định của phân thức', formula: '$\\f{A}{B}$ xác định $\\Leftrightarrow B\\ne0$', usage: 'Bước bắt buộc đầu tiên của mọi bài phân thức.', trap: 'Phân tích mẫu thành nhân tử rồi cho **từng** nhân tử khác $0$ — đừng bỏ sót nghiệm nào.' },
  { id: 'f8-25', grade: 8, strand: 'SO_DAI_SO', topic: 'Phân thức', name: 'Bốn phép tính với phân thức', formula: '$\\f{A}{B}\\pm\\f{C}{D}$: quy đồng rồi cộng trừ tử · $\\f{A}{B}\\cdot\\f{C}{D}=\\f{AC}{BD}$ · $\\f{A}{B}:\\f{C}{D}=\\f{A}{B}\\cdot\\f{D}{C}$', condition: '$B$, $D\\ne0$; phép chia cần $C\\ne0$', usage: 'Rút gọn biểu thức hữu tỉ.', trap: 'Chỉ được rút gọn **nhân tử chung**, không rút từng hạng tử của một tổng.' },
  { id: 'f8-26', grade: 8, strand: 'SO_DAI_SO', topic: 'Phương trình', name: 'Số nghiệm của $ax+b=0$', formula: '$a\\ne0$: một nghiệm $x=-\\f{b}{a}$ · $a=0$, $b\\ne0$: **vô nghiệm** · $a=b=0$: **vô số nghiệm**', usage: 'Biện luận phương trình bậc nhất có tham số.', trap: 'Ba trường hợp rất dễ lẫn — luôn xét dấu của $a$ trước.' },
  { id: 'f8-27', grade: 8, strand: 'SO_DAI_SO', topic: 'Phương trình', name: 'Phương trình tích', formula: '$A\\cdot B=0\\Leftrightarrow A=0$ hoặc $B=0$', usage: 'Giải phương trình bậc cao sau khi phân tích thành nhân tử.', trap: 'Phải giải **hết** các nhánh; bỏ một nhánh là mất nghiệm.' },
  { id: 'f8-28', grade: 8, strand: 'SO_DAI_SO', topic: 'Lập phương trình', name: 'Ba bước lập phương trình', formula: '1) Gọi ẩn kèm **đơn vị và điều kiện** · 2) Lập phương trình · 3) Giải và **đối chiếu điều kiện**', usage: 'Mọi bài toán đố giải bằng cách lập phương trình.', trap: 'Thiếu bước đặt điều kiện hoặc bước đối chiếu là mất điểm dù tính đúng.' },
  { id: 'f8-29', grade: 8, strand: 'SO_DAI_SO', topic: 'Hàm số', name: 'Vị trí tương đối của hai đường thẳng', formula: 'Cắt nhau $\\Leftrightarrow a\\ne a\'$ · Song song $\\Leftrightarrow a=a\'$, $b\\ne b\'$ · Trùng nhau $\\Leftrightarrow a=a\'$, $b=b\'$', usage: 'Bài toán tham số về hai đường thẳng.', trap: 'Song song phải kèm $b\\ne b\'$; thiếu điều kiện này thì hai đường có thể **trùng** nhau.' },
  { id: 'f8-30', grade: 8, strand: 'SO_DAI_SO', topic: 'Hàm số', name: 'Giao điểm với hai trục toạ độ', formula: 'Giao trục tung: cho $x=0$, được $(0;b)$ · Giao trục hoành: cho $y=0$, được $\\left(-\\f{b}{a};0\\right)$', usage: 'Vẽ đồ thị hàm số bậc nhất bằng hai điểm.', trap: 'Tung độ gốc chính là $b$ — đọc thẳng từ công thức, không cần tính.' },
  { id: 'f8-31', grade: 8, strand: 'HINH_HOC', topic: 'Tứ giác', name: 'Sơ đồ nhận biết tứ giác đặc biệt', formula: 'Hình bình hành $+$ một góc vuông (hoặc hai chéo bằng nhau) $\\to$ **chữ nhật** · $+$ hai cạnh kề bằng nhau (hoặc hai chéo vuông góc) $\\to$ **thoi** · có cả hai $\\to$ **vuông**', usage: 'Bài chứng minh tứ giác là hình đặc biệt.', trap: 'Phải chứng minh là hình bình hành **trước**, rồi mới thêm điều kiện.' },
  { id: 'f8-32', grade: 8, strand: 'HINH_HOC', topic: 'Đường trung bình', name: 'Đường trung bình tam giác và hình thang', formula: 'Tam giác: $MN\\para BC$ và $MN=\\f{BC}{2}$ · Hình thang: $MN\\para$ hai đáy và $MN=\\f{AB+CD}{2}$', usage: 'Tạo quan hệ song song và tính độ dài.', trap: 'Tam giác lấy **nửa cạnh**, hình thang lấy **nửa tổng hai đáy**.' },
  { id: 'f8-33', grade: 8, strand: 'HINH_HOC', topic: 'Đồng dạng', name: 'Ba trường hợp đồng dạng', formula: 'c.c.c (ba cạnh tỉ lệ) · c.g.c (hai cạnh tỉ lệ, góc xen giữa bằng nhau) · **g.g** (hai góc bằng nhau)', usage: 'Chứng minh hai tam giác đồng dạng.', trap: 'Ưu tiên **g.g** — nhanh nhất vì góc dễ tìm hơn cạnh.' },
  { id: 'f8-34', grade: 8, strand: 'HINH_HOC', topic: 'Đồng dạng', name: 'Tỉ số các đại lượng của tam giác đồng dạng', formula: 'Cạnh, chu vi, đường cao, trung tuyến, phân giác: tỉ số $=k$ · **Diện tích**: tỉ số $=k^{2}$', usage: 'Tính chu vi, diện tích khi biết tỉ số đồng dạng.', trap: 'Chỉ **diện tích** mới lấy $k^{2}$; mọi đại lượng độ dài đều lấy $k$.' },
  { id: 'f8-35', grade: 8, strand: 'HINH_HOC', topic: 'Hình chóp', name: 'Hình chóp đều', formula: '$S_{xq}=\\f{1}{2}C_{\\text{đáy}}\\cdot d$ ($d$ là **trung đoạn**) · $S_{tp}=S_{xq}+S_{\\text{đáy}}$ · $V=\\f{1}{3}S_{\\text{đáy}}\\cdot h$', usage: 'Bài toán hình chóp tam giác đều, tứ giác đều.', trap: 'Trung đoạn nằm **trên mặt bên** (cho diện tích); chiều cao nằm **bên trong** (cho thể tích).' },
  { id: 'f8-36', grade: 8, strand: 'THONG_KE_XS', topic: 'Xác suất', name: 'Xác suất lí thuyết và thực nghiệm', formula: 'Lí thuyết $=\\f{\\text{số kết quả thuận lợi}}{\\text{tổng số kết quả đồng khả năng}}$ · Thực nghiệm $=\\f{\\text{số lần xảy ra}}{\\text{số lần thử}}$', usage: 'Phân biệt hai loại xác suất trong đề.', trap: 'Xác suất thực nghiệm chỉ **xấp xỉ** lí thuyết; càng nhiều lần thử càng gần.' },

  /* ============================== LỚP 9 ============================== */
  { id: 'f9-29', grade: 9, strand: 'SO_DAI_SO', topic: 'Căn thức', name: 'Điều kiện xác định của căn thức', formula: '$\\s{A}$ xác định $\\Leftrightarrow A\\ge0$ · $\\f{1}{\\s{A}}$ xác định $\\Leftrightarrow A>0$', usage: 'Bước đầu tiên của mọi bài căn thức.', trap: 'Căn ở **mẫu** thì điều kiện chặt hơn: phải $>0$ chứ không phải $\\ge0$.' },
  { id: 'f9-30', grade: 9, strand: 'SO_DAI_SO', topic: 'Căn thức', name: 'Căn kép', formula: '$a\\pm2\\s{b}=(\\s{m}\\pm\\s{n})^{2}$ với $m+n=a$, $mn=b$', usage: 'Rút gọn biểu thức có căn lồng trong căn.', trap: 'Khi khai căn phải lấy giá trị tuyệt đối và **xét dấu** để bỏ dấu đó.' },
  { id: 'f9-31', grade: 9, strand: 'SO_DAI_SO', topic: 'Bất phương trình', name: 'Quy tắc biến đổi bất phương trình', formula: 'Nhân/chia hai vế cho số **dương**: giữ chiều · cho số **âm**: **ĐỔI CHIỀU**', usage: 'Giải bất phương trình bậc nhất một ẩn.', trap: 'Mẫu chứa ẩn thì chưa biết dấu — chuyển về một vế rồi xét dấu, không nhân chéo.' },
  { id: 'f9-32', grade: 9, strand: 'SO_DAI_SO', topic: 'Bất đẳng thức', name: 'Cauchy – Schwarz dạng cộng mẫu', formula: '$\\f{a^{2}}{x}+\\f{b^{2}}{y}\\ge\\f{(a+b)^{2}}{x+y}$', condition: '$x$, $y>0$', usage: 'Cực trị của tổng phân thức có tử là bình phương.', trap: 'Dấu $=$ khi $\\f{a}{x}=\\f{b}{y}$ — luôn phải nêu điều kiện này.' },
  { id: 'f9-33', grade: 9, strand: 'SO_DAI_SO', topic: 'Bất đẳng thức', name: 'Bunhiacopxki', formula: '$(a^{2}+b^{2})(x^{2}+y^{2})\\ge(ax+by)^{2}$', usage: 'Đề cho tổng bình phương, hỏi tổng bậc nhất (hoặc ngược lại).', trap: 'Dấu $=$ khi $\\f{a}{x}=\\f{b}{y}$; kết quả là chặn **hai phía** nên phải chọn dấu.' },
  { id: 'f9-34', grade: 9, strand: 'SO_DAI_SO', topic: 'Phương trình bậc hai', name: 'Điều kiện về dấu hai nghiệm', formula: 'Trái dấu $\\Leftrightarrow P<0$ · Cùng dương $\\Leftrightarrow \\Delta>0$, $S>0$, $P>0$ · Cùng âm $\\Leftrightarrow \\Delta>0$, $S<0$, $P>0$', usage: 'Bài toán tham số về dấu của nghiệm.', trap: 'Trường hợp trái dấu **không cần** thêm $\\Delta>0$ vì $P<0$ đã kéo theo.' },
  { id: 'f9-35', grade: 9, strand: 'SO_DAI_SO', topic: 'Viète', name: 'Viète đảo', formula: 'Hai số có tổng $S$, tích $P$ là nghiệm của $x^{2}-Sx+P=0$', condition: '$S^{2}-4P\\ge0$', usage: 'Tìm hai số biết tổng và tích.', trap: 'Hệ số của $x$ là $-S$ — **đổi dấu** tổng.' },
  { id: 'f9-36', grade: 9, strand: 'SO_DAI_SO', topic: 'Hàm số', name: 'Đồ thị hàm số $y=ax^{2}$', formula: 'Parabol đỉnh $O$, trục đối xứng $Oy$ · $a>0$: bề lõm hướng lên, $O$ là điểm **thấp nhất** · $a<0$: ngược lại', usage: 'Bài toán tương giao parabol và đường thẳng.', trap: 'Hoành độ giao điểm là nghiệm của phương trình hoành độ giao điểm.' },
  { id: 'f9-37', grade: 9, strand: 'HINH_HOC', topic: 'Hệ thức lượng', name: 'Bốn hệ thức trong tam giác vuông', formula: '$b^{2}=ab\'$ · $c^{2}=ac\'$ · $h^{2}=b\'c\'$ · $ah=bc$ · $\\f{1}{h^{2}}=\\f{1}{b^{2}}+\\f{1}{c^{2}}$', usage: 'Tam giác vuông có đường cao ứng với cạnh huyền.', trap: '$h^{2}$ bằng tích hai **hình chiếu**, không phải tích hai cạnh góc vuông.' },
  { id: 'f9-38', grade: 9, strand: 'HINH_HOC', topic: 'Lượng giác', name: 'Tỉ số lượng giác của hai góc phụ nhau', formula: '$\\sin\\alpha=\\cos(90\\deg-\\alpha)$ · $\\tan\\alpha=\\cot(90\\deg-\\alpha)$', usage: 'Đổi giữa các tỉ số lượng giác, rút gọn biểu thức.', trap: 'Hai góc phụ nhau đổi vai trò cạnh đối và cạnh kề cho nhau.' },
  { id: 'f9-39', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Vị trí tương đối của hai đường tròn', formula: '$d>R+r$: ngoài nhau · $d=R+r$: tiếp xúc ngoài · $|R-r|<d<R+r$: cắt nhau · $d=|R-r|$: tiếp xúc trong · $d<|R-r|$: đựng nhau', usage: 'Câu nhận biết về hai đường tròn.', trap: 'Mốc dưới luôn là **giá trị tuyệt đối** $|R-r|$.' },
  { id: 'f9-40', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Đa giác đều nội tiếp $(O;R)$', formula: 'Cạnh $=2R\\sin\\f{180\\deg}{n}$ · Tam giác đều $R\\s{3}$ · Hình vuông $R\\s{2}$ · Lục giác đều $R$', usage: 'Tính cạnh, chu vi của đa giác đều nội tiếp.', trap: 'Nhớ theo dãy $\\s{3}$, $\\s{2}$, $1$ ứng với $3$, $4$, $6$ cạnh.' },
  { id: 'f9-41', grade: 9, strand: 'HINH_HOC', topic: 'Đường tròn', name: 'Độ dài cung và diện tích hình quạt', formula: '$\\ell=\\f{\\pi Rn}{180}$ · $S_{\\text{quạt}}=\\f{\\pi R^{2}n}{360}=\\f{\\ell R}{2}$', usage: 'Tính độ dài cung, diện tích hình quạt tròn.', trap: 'Mẫu $180$ cho **độ dài cung**, mẫu $360$ cho **diện tích** — rất dễ lẫn.' },
  { id: 'f9-42', grade: 9, strand: 'HINH_HOC', topic: 'Hình khối tròn xoay', name: 'Hình nón', formula: '$l^{2}=r^{2}+h^{2}$ · $S_{xq}=\\pi rl$ · $S_{tp}=\\pi rl+\\pi r^{2}$ · $V=\\f{1}{3}\\pi r^{2}h$', usage: 'Bài toán hình nón, nón cụt, khối ghép.', trap: 'Diện tích xung quanh dùng **đường sinh** $l$; thể tích dùng **chiều cao** $h$.' },
  { id: 'f9-43', grade: 9, strand: 'HINH_HOC', topic: 'Hình khối tròn xoay', name: 'Hình trụ và hình cầu', formula: 'Trụ: $S_{xq}=2\\pi rh$, $V=\\pi r^{2}h$ · Cầu: $S=4\\pi R^{2}$, $V=\\f{4}{3}\\pi R^{3}$', usage: 'Bài toán bể chứa, quả bóng, khối ghép.', trap: 'Đề thường cho **đường kính** — nhớ chia đôi để lấy bán kính.' },
  { id: 'f9-44', grade: 9, strand: 'THONG_KE_XS', topic: 'Thống kê', name: 'Bảng tần số ghép nhóm', formula: 'Giá trị đại diện $=$ trung điểm nhóm · Trung bình $=\\f{\\sum(\\text{đại diện}\\times\\text{tần số})}{N}$', usage: 'Tính số trung bình từ bảng ghép nhóm.', trap: 'Lấy đầu mút nhóm thay vì **trung điểm** là sai công thức.' },
  { id: 'f9-45', grade: 9, strand: 'THONG_KE_XS', topic: 'Xác suất', name: 'Biến cố đối', formula: '$P(A)=1-P(\\ov{A})$', usage: 'Biến cố dạng "**ít nhất một**" — tính qua biến cố đối cho nhanh.', trap: 'Đừng quên bước cuối lấy $1$ trừ đi.' },
];
